# Generated by Django 4.0.2 on 2022-02-25 00:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 0, 28, 9, 856738, tzinfo=utc)),
        ),
    ]
