# Generated by Django 4.0.2 on 2022-02-25 03:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_rename_telfone_contato_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 3, 5, 46, 602964, tzinfo=utc)),
        ),
    ]
