# Generated by Django 4.0.2 on 2022-03-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_contato_fotos'),
        ('contatos', '0004_contato_mostrar_alter_contato_data_criacao'),
    ]

    operations = [
    ]
